In [1]:
import pandas as pd 
import numpy as np
from sklearn import decomposition
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("Student.csv")

In [3]:
dataset.head()

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Hours working per day,...,Interested Type of Books,Salary Range Expected,In a Realtionship?,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,69,63,78,87,94,94,87,84,61,9,...,Prayer books,salary,no,stubborn,Management,salary,hard worker,yes,no,Database Developer
1,78,62,73,60,71,70,73,84,91,12,...,Childrens,salary,yes,gentle,Technical,salary,hard worker,no,yes,Portal Administrator
2,71,86,91,87,61,81,72,72,94,11,...,Travel,Work,no,stubborn,Management,work,hard worker,no,yes,Portal Administrator
3,76,87,60,84,89,73,62,88,69,7,...,Romance,Work,yes,gentle,Management,work,smart worker,yes,yes,Systems Security Administrator
4,92,62,90,67,71,89,73,71,73,4,...,Cookbooks,salary,no,stubborn,Management,work,hard worker,yes,yes,Business Systems Analyst

In [4]:
data = dataset.iloc[:,:-1].values
label = dataset.iloc[:,-1].values
len(data[0])

38

In [5]:
dataset.iloc[:,10:46]

,Logical quotient rating,hackathons,coding skills rating,public speaking points,can work long time before system?,self-learning capability?,Extra-courses did,certifications,workshops,talenttests taken?,...,Interested Type of Books,Salary Range Expected,In a Realtionship?,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,4,0,4,8,yes,yes,yes,shell programming,cloud computing,no,...,Prayer books,salary,no,stubborn,Management,salary,hard worker,yes,no,Database Developer
1,7,1,2,3,yes,no,yes,machine learning,database security,no,...,Childrens,salary,yes,gentle,Technical,salary,hard worker,no,yes,Portal Administrator
2,1,4,1,3,yes,no,yes,app development,web technologies,no,...,Travel,Work,no,stubborn,Management,work,hard worker,no,yes,Portal Administrator
3,1,1,2,5,no,yes,no,python,data science,yes,...,Romance,Work,yes,gentle,Management,work,smart worker,yes,yes,Systems Security Administrator
4,5,4,6,3,no,no,no,app development,cloud computing,no,...,Cookbooks,salary,no,stubborn,Management,work,hard worker,yes,yes,Business Systems Analyst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,2,6,1,8,yes,no,no,app development,cloud computing,yes,...,Journals,Work,yes,stubborn,Management,salary,smart worker,yes,no,Technical Engineer
19996,8,0,9,8,yes,no,no,full stack,game development,no,...,Cookbooks,salary,no,stubborn,Management,salary,hard worker,no,yes,E-Commerce Analyst
19997,3,6,2,3,yes,yes,yes,information security,database security,yes,...,Drama,Work,yes,gentle,Technical,work,hard worker,no,yes,Business Intelligence Analyst
19998,1,4,9,5,no,no,no,full stack,cloud computing,no,...,Travel,Work,no,gentle,Management,work,smart worker,yes,no,Software Quality Assurance (QA) / Testing
19999,3,1,7,6,yes,yes,yes,app development,database security,no,...,Comics,Work,no,gentle,Management,work,hard worker,yes,no,Applications Developer

In [6]:

dataset.iloc[:,:12]

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Hours working per day,Logical quotient rating,hackathons
0,69,63,78,87,94,94,87,84,61,9,4,0
1,78,62,73,60,71,70,73,84,91,12,7,1
2,71,86,91,87,61,81,72,72,94,11,1,4
3,76,87,60,84,89,73,62,88,69,7,1,1
4,92,62,90,67,71,89,73,71,73,4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...
19995,83,67,62,63,81,74,90,84,69,4,2,6
19996,80,69,83,87,82,66,66,92,67,7,8,0
19997,83,70,80,87,64,85,69,94,88,7,3,6
19998,68,87,91,88,66,74,61,87,61,5,1,4
19999,73,77,74,84,70,65,92,73,90,7,3,1

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [8]:
labelencoder = LabelEncoder()

In [9]:
for i in range(14,38):
    data[:,i] = labelencoder.fit_transform(data[:,i])
data[:5]

array([[69, 63, 78, 87, 94, 94, 87, 84, 61, 9, 4, 0, 4, 8, 1, 1, 1, 8, 0,
        0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0, 0, 1, 0],
       [78, 62, 73, 60, 71, 70, 73, 84, 91, 12, 7, 1, 2, 3, 1, 0, 1, 5,
        2, 0, 0, 2, 1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0, 0, 1],
       [71, 86, 91, 87, 61, 81, 72, 72, 94, 11, 1, 4, 1, 3, 1, 0, 1, 0,
        7, 0, 1, 2, 0, 6, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1, 0, 0, 1],
       [76, 87, 60, 84, 89, 73, 62, 88, 69, 7, 1, 1, 2, 5, 0, 1, 0, 6, 1,
        1, 0, 1, 0, 7, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1, 1, 1, 1],
       [92, 62, 90, 67, 71, 89, 73, 71, 73, 4, 5, 4, 6, 3, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0, 1, 1]],
      dtype=object)

In [10]:
data[:7,14:]

array([[1, 1, 1, 8, 0, 0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0,
        0, 1, 0],
       [1, 0, 1, 5, 2, 0, 0, 2, 1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0,
        0, 1],
       [1, 0, 1, 0, 7, 0, 1, 2, 0, 6, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1,
        0, 0, 1],
       [0, 1, 0, 6, 1, 1, 0, 1, 0, 7, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1,
        1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0,
        1, 1],
       [1, 1, 0, 6, 2, 0, 0, 2, 1, 9, 4, 1, 7, 1, 1, 27, 1, 0, 1, 0, 1,
        1, 1, 0],
       [0, 0, 1, 7, 0, 0, 0, 0, 2, 8, 3, 1, 0, 0, 0, 10, 0, 1, 0, 1, 0,
        0, 1, 1]], dtype=object)

In [11]:
from sklearn.preprocessing import Normalizer

In [12]:
data1=data[:,:14]

In [13]:
normalized_data = Normalizer().fit_transform(data1)
print(normalized_data.shape)

(20000, 14)

In [14]:
normalized_data

array([[0.28508989, 0.26029947, 0.32227553, ..., 0.        , 0.01652695,
        0.0330539 ],
       [0.34997994, 0.27818918, 0.32754533, ..., 0.00448692, 0.00897384,
        0.01346077],
       [0.29501244, 0.35733901, 0.37811453, ..., 0.01662042, 0.0041551 ,
        0.01246531],
       ...,
       [0.3430836 , 0.28934762, 0.33068299, ..., 0.02480122, 0.00826707,
        0.01240061],
       [0.29479246, 0.37716094, 0.39450167, ..., 0.01734073, 0.03901665,
        0.02167592],
       [0.31140896, 0.32847247, 0.31567484, ..., 0.00426588, 0.02986113,
        0.02559526]])

In [15]:
data2=data[:,14:]
data2.shape

(20000, 24)

In [16]:
df1 = np.append(normalized_data,data2,axis=1)
df1.shape

(20000, 38)

# Adding labels

In [17]:
X1 = pd.DataFrame(df1,columns=['Acedamic percentage in Operating Systems', 'percentage in Algorithms',
       'Percentage in Programming Concepts',
       'Percentage in Software Engineering', 'Percentage in Computer Networks',
       'Percentage in Electronics Subjects',
       'Percentage in Computer Architecture', 'Percentage in Mathematics',
       'Percentage in Communication skills', 'Hours working per day',
       'Logical quotient rating', 'hackathons', 'coding skills rating',
       'public speaking points', 'can work long time before system?',
       'self-learning capability?', 'Extra-courses did', 'certifications',
       'workshops', 'talenttests taken?', 'olympiads',
       'reading and writing skills', 'memory capability score',
       'Interested subjects', 'interested career area ', 'Job/Higher Studies?',
       'Type of company want to settle in?',
       'Taken inputs from seniors or elders', 'interested in games',
       'Interested Type of Books', 'Salary Range Expected',
       'In a Realtionship?', 'Gentle or Tuff behaviour?',
       'Management or Technical', 'Salary/work', 'hard/smart worker',
       'worked in teams ever?', 'Introvert'])

In [18]:
X1.head()

,Acedamic percentage in Operating Systems,percentage in Algorithms,Percentage in Programming Concepts,Percentage in Software Engineering,Percentage in Computer Networks,Percentage in Electronics Subjects,Percentage in Computer Architecture,Percentage in Mathematics,Percentage in Communication skills,Hours working per day,...,interested in games,Interested Type of Books,Salary Range Expected,In a Realtionship?,Gentle or Tuff behaviour?,Management or Technical,Salary/work,hard/smart worker,worked in teams ever?,Introvert
0,0.28509,0.260299,0.322276,0.359461,0.388383,0.388383,0.359461,0.347066,0.252036,0.037186,...,0,21,1,0,1,0,0,0,1,0
1,0.34998,0.278189,0.327545,0.269215,0.318571,0.314085,0.327545,0.376901,0.40831,0.053843,...,1,5,1,1,0,1,0,0,0,1
2,0.295012,0.357339,0.378115,0.361494,0.253461,0.336563,0.299168,0.299168,0.39058,0.045706,...,1,29,0,0,1,0,1,0,0,1
3,0.328025,0.375503,0.258967,0.362554,0.384135,0.315077,0.2676,0.379819,0.297812,0.030213,...,0,23,0,1,0,0,1,1,1,1
4,0.397157,0.267649,0.388523,0.289234,0.306502,0.384206,0.315136,0.306502,0.315136,0.017268,...,1,7,1,0,1,0,1,0,1,1

In [19]:
label = labelencoder.fit_transform(label)
print(len(label))

20000

In [20]:
y=pd.DataFrame(label,columns=["Suggested Job Role"])
y.head()

   Suggested Job Role
0                   7
1                  18
2                  18
3                  28
4                   2

# Decision Tree Classifier

In [21]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.2,random_state=10)

In [23]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [24]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [25]:
y_pred = clf.predict(X_test)

In [26]:
y_pred

array([24,  6,  5, ..., 23, 28, 28])

In [27]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)

In [28]:
print("confusion matrics=",cm)
print("  ")
print("accuracy=",accuracy*100)

confusion matrics= [[2 8 2 ... 3 4 3]
 [3 2 3 ... 7 2 3]
 [3 1 0 ... 3 2 4]
 ...
 [3 2 3 ... 4 2 5]
 [6 3 2 ... 6 2 4]
 [5 5 2 ... 2 2 2]]

accuracy= 2.875

#  Decision tree with entropy

In [29]:
clf_entropy = tree.DecisionTreeClassifier(criterion = "entropy", random_state = 10)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=10)

In [30]:
entropy_y_pred=clf_entropy.predict(X_test)

In [31]:
cm_entopy = confusion_matrix(y_test,entropy_y_pred)

In [32]:
entropy_accuracy = accuracy_score(y_test,entropy_y_pred)

In [33]:
print("confusion matrics=",cm_entopy)
print("  ")
print("accuracy=",entropy_accuracy*100)

confusion matrics= [[1 3 7 ... 3 2 2]
 [2 4 3 ... 3 2 4]
 [1 2 4 ... 0 3 1]
 ...
 [1 6 3 ... 0 5 2]
 [3 2 4 ... 2 2 4]
 [5 1 6 ... 6 6 4]]

accuracy= 2.7

# SVM (Support vector machine) classifier

In [34]:
from sklearn import svm

In [35]:
clf = svm.SVC()
clf.fit(X_train, y_train)

D:\Anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

SVC()

In [36]:
svm_y_pred = clf.predict(X_test)

In [37]:
svm_cm = confusion_matrix(y_test,svm_y_pred)
svm_accuracy = accuracy_score(y_test,svm_y_pred)

In [38]:
print("confusion matrics=",svm_cm)
print("  ")
print("accuracy=",svm_accuracy*100)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

accuracy= 5.6000000000000005

# xgboost

In [39]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.3,random_state=10)

In [40]:
X_train.shape

(14000, 38)

In [41]:
X_train=pd.to_numeric(X_train.values.flatten())

In [42]:
X_train=X_train.reshape((14000,38))

In [43]:
from xgboost import XGBClassifier

In [44]:
model = XGBClassifier()
model.fit(X_train, y_train)

D:\Anaconda\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
D:\Anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

[13:19:15] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=4, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [45]:
xgb_y_pred = clf.predict(X_test)

In [46]:
xgb_cm = confusion_matrix(y_test,xgb_y_pred)
xgb_accuracy = accuracy_score(y_test,xgb_y_pred)

In [47]:
print("confusion matrics=",xgb_cm)
print("  ")
print("accuracy=",xgb_accuracy*100)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

accuracy= 5.75